"""
This test case checks if the images generated by code in outputs are then stored properly as files and not dumped
as base64 encoded raw strings directly into markdown cell
"""
from IPython.display import Image

Image(data=bytes("abc", "utf-8"))
